name: WarpPvp
version: ${project.version}
main: com.anywhich.mc.warppvp.WarpPvp
api-version: 1.16
commands:
  warp:
    description: Warp pvp minigame
    usage: /<command>
    permission: warp-pvp.warp
